name: dev-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip==23.1.2
  - matplotlib==3.7.1
  - seaborn==0.12.2
  - scikit-learn==1.3.0
  - py-xgboost==1.7.3
  - lightgbm=3.3.5
  - pyyaml==6.0
  - pyarrow==12.0.1
  - fastparquet==2023.4.0
  - imbalanced-learn==0.10.1
  - shap==0.42.1
  - black==23.3.0
  - pip:
    - pandas==2.0.2
    - optuna==3.2.0
    - mlflow==2.4.0
